# Generated by Django 4.0.4 on 2022-06-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_created_by_alter_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='executive',
            new_name='executor',
        ),
    ]
