# Generated by Django 4.0.4 on 2022-05-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id'], 'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
